### ISSUE TITLE
Architecture update on Figure 2

### ISSUE THREAD

**Issue by cheneyzhoucheng** [cheneyzhoucheng/network-digital-twin#10]
- Inner closed-loop: iterative simulation and verification in twin layer. Outer closed-loop validation and optimization.
- Orchestration for models and resources can be included in NDT mgmt module 
- etc.

**Comment by billwuqin** [comment]
Related to scope of NDT. We need to decide how to separate network digital twin as a tool from network managemet sytem or orchestrator

**Comment by cfjanz** [comment]
Sorry for jumping in late. As you know, my "criticisms" were that the NDT was too closely identified functionally as a controller, and that the presentation of architecture left major gaps between the modeling function and the remainder (e.g., inner and outer closed loops were not discussed or depicted). That said, I think the presentation and discussion at Brisbane show we do in fact have a pretty close conceptual view. You proposed there to reorient the draft toward "concept only" and in fact Colin advised that IRTF should not get into architecture; I think that's a little over the top but in any case.

**Comment by cfjanz** [comment]
I think it is possible to split the difference, by describing architecture on a high level, conceptual basis. Describe a core function based on data and modeling; then describe the composition of closed loops using that core function plus others; then describe how those closed loops can be used in automation architectures (some of which might be controllers, some might be limited to planning and management, etc.) In this description, I think it is easiest to call the "core function" the NDT (full stop), but you can call it the NDT core functions if you still prefer some ambiguity. Once that's done, it is easy to consider use cases.
