### ISSUE TITLE
NDT characteristic vs NDT elements

### ISSUE THREAD

**Issue by billwuqin** [cheneyzhoucheng/network-digital-twin#7]

**Comment by billwuqin** [comment]
Data, Model, Mapping, Interface are four NDT characterisitcs or four phase of NDT lifecycle management?
where do we position emulation?

**Comment by boucadair** [comment]
> Data, Model, Mapping, Interface are four NDT characterisitcs or four phase of NDT lifecycle management?

These are not phases.

> where do we position emulation?

emulate/control/diag/etc. are core functions of the twin engine.

**Comment by cfjanz** [comment]
I don't understand how it makes sense to call a range of functions as broad as emulation, diagnosis, control, "etc." as a "core functions" of an engine. It's tantamount to saying an NDT does anything and everything. Doesn't it make more sense to talk about NDT core functions that are closer to emulation/modeling based on network data, and then show how those core functions can be composed with other functions, to construct progressively more complex engines that serve different applications?
