### ISSUE TITLE
Clarification on Bi-directional interaction

### ISSUE THREAD

**Issue by cheneyzhoucheng** [cheneyzhoucheng/network-digital-twin#9]
- It is not possible or necessary to 'synchronize' all twin states or flows to physical entity. 
- Bi-directional interaction means that: data/states/flows reported or collected from physical to twin, and configure changes or 'necessary' data sent from twin to physical.

**Comment by billwuqin** [comment]
Clarified in https://github.com/cheneyzhoucheng/network-digital-twin/commit/efab85d6d080deab03c15417978f1e0a7c55e6dc

**Comment by boucadair** [comment]
> * It is not possible or necessary to 'synchronize' all twin states or flows to physical entity.

@billwuqin, I suggest we add an explicit sentence to indicate that "the mirroring pace and scope" should be controlled for a given twin instance.

**Comment by billwuqin** [comment]
Good comment, we haven't explored  mirroring pace and scope.  I think mirroring pace and scope needs to be further expanded.
